services:
  graphql-gateway:
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    container_name: graphql-gateway
    environment:
      PORT: "4000"
      SHIPPING_DGS_URL: "http://shipping-dgs:4004/graphql"
      PRODUCT_CATALOG_DGS_URL: "http://product-catalog-dgs:4005/graphql"
      CURRENCY_DGS_URL: "http://currency-dgs:4006/graphql"
      CART_DGS_URL: "http://cart-dgs:4007/graphql"
    ports:
      - "4000:4000"
    depends_on:
      - shipping-dgs
      - product-catalog-dgs
      - currency-dgs
      - cart-dgs
  shipping-dgs:
    build:
      context: ./src/shipping-dgs
      dockerfile: Dockerfile
    container_name: shipping-dgs
    environment:
      PORT: 4004
      SHIPPING_ADDR: http://shipping:50050
    ports:
      - "4004:4004"
    depends_on:
      - shipping
  product-catalog-dgs:
    build:
      context: ./src/product-catalog-dgs
      dockerfile: Dockerfile
    container_name: product-catalog-dgs
    environment:
      PORT: "4005"
      PRODUCT_CATALOG_ADDR: "product-catalog:3550"
    ports:
      - "4005:4005"
    depends_on:
      - product-catalog
  currency-dgs:
    build:
      context: ./src/currency-dgs
      dockerfile: Dockerfile
    container_name: currency-dgs
    environment:
      PORT: "4006"
      CURRENCY_ADDR: "currency:7001"
    ports:
      - "4006:4006"
    depends_on:
      - currency
  cart-dgs:
    build:
      context: ./src/cart-dgs
      dockerfile: Dockerfile
    container_name: cart-dgs
    environment:
      PORT: "4007"
      CART_ADDR: "cart:7070"
    ports:
      - "4007:4007"
    depends_on:
      - cart